line_length:
  warning: 180
  error:   200

function_body_length:
  warning: 25
  error:   30

type_body_length:
  warning: 250
  error:   300

file_length:
  warning: 250
  error:   300

force_cast:
  severity: warning

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_parameters
  - nimble_operator
  - number_separator
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - single_test_class
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  - identifier_name # annoying

  - colon                   # align properties
  - comma                   # align func params
  - return_arrow_whitespace # align return type

  - opening_brace      # if true { ... }
  - statement_position # else    { ... }

included:
  - SwiftBoy
  - CodeGen
  - Tests
