// This file was auto-generated.
// DO NOT EDIT!

// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length
// swiftlint:disable function_body_length
// swiftlint:disable cyclomatic_complexity

extension Cpu {
  mutating func execute(_ opcode: PrefixOpcode) {
    switch opcode.type {
    case .rlc_b_00: rlc_r(.b)
    case .rlc_c_01: rlc_r(.c)
    case .rlc_d_02: rlc_r(.d)
    case .rlc_e_03: rlc_r(.e)
    case .rlc_h_04: rlc_r(.h)
    case .rlc_l_05: rlc_r(.l)
    case .rlc_pHL_06: rlc_pHL()
    case .rlc_a_07: rlc_r(.a)
    case .rrc_b_08: rrc_r(.b)
    case .rrc_c_09: rrc_r(.c)
    case .rrc_d_0a: rrc_r(.d)
    case .rrc_e_0b: rrc_r(.e)
    case .rrc_h_0c: rrc_r(.h)
    case .rrc_l_0d: rrc_r(.l)
    case .rrc_pHL_0e: rrc_pHL()
    case .rrc_a_0f: rrc_r(.a)
    case .rl_b_10: rl_r(.b)
    case .rl_c_11: rl_r(.c)
    case .rl_d_12: rl_r(.d)
    case .rl_e_13: rl_r(.e)
    case .rl_h_14: rl_r(.h)
    case .rl_l_15: rl_r(.l)
    case .rl_pHL_16: rl_pHL()
    case .rl_a_17: rl_r(.a)
    case .rr_b_18: rr_r(.b)
    case .rr_c_19: rr_r(.c)
    case .rr_d_1a: rr_r(.d)
    case .rr_e_1b: rr_r(.e)
    case .rr_h_1c: rr_r(.h)
    case .rr_l_1d: rr_r(.l)
    case .rr_pHL_1e: rr_pHL()
    case .rr_a_1f: rr_r(.a)
    case .sla_b_20: sla_r(.b)
    case .sla_c_21: sla_r(.c)
    case .sla_d_22: sla_r(.d)
    case .sla_e_23: sla_r(.e)
    case .sla_h_24: sla_r(.h)
    case .sla_l_25: sla_r(.l)
    case .sla_pHL_26: sla_pHL()
    case .sla_a_27: sla_r(.a)
    case .sra_b_28: sra_r(.b)
    case .sra_c_29: sra_r(.c)
    case .sra_d_2a: sra_r(.d)
    case .sra_e_2b: sra_r(.e)
    case .sra_h_2c: sra_r(.h)
    case .sra_l_2d: sra_r(.l)
    case .sra_pHL_2e: sra_pHL()
    case .sra_a_2f: sra_r(.a)
    case .swap_b_30: swap_r(.b)
    case .swap_c_31: swap_r(.c)
    case .swap_d_32: swap_r(.d)
    case .swap_e_33: swap_r(.e)
    case .swap_h_34: swap_r(.h)
    case .swap_l_35: swap_r(.l)
    case .swap_pHL_36: swap_pHL()
    case .swap_a_37: swap_r(.a)
    case .srl_b_38: srl_r(.b)
    case .srl_c_39: srl_r(.c)
    case .srl_d_3a: srl_r(.d)
    case .srl_e_3b: srl_r(.e)
    case .srl_h_3c: srl_r(.h)
    case .srl_l_3d: srl_r(.l)
    case .srl_pHL_3e: srl_pHL()
    case .srl_a_3f: srl_r(.a)
    case .bit_0_b_40: bit_r(0, .b)
    case .bit_0_c_41: bit_r(0, .c)
    case .bit_0_d_42: bit_r(0, .d)
    case .bit_0_e_43: bit_r(0, .e)
    case .bit_0_h_44: bit_r(0, .h)
    case .bit_0_l_45: bit_r(0, .l)
    case .bit_0_pHL_46: bit_pHL(0)
    case .bit_0_a_47: bit_r(0, .a)
    case .bit_1_b_48: bit_r(1, .b)
    case .bit_1_c_49: bit_r(1, .c)
    case .bit_1_d_4a: bit_r(1, .d)
    case .bit_1_e_4b: bit_r(1, .e)
    case .bit_1_h_4c: bit_r(1, .h)
    case .bit_1_l_4d: bit_r(1, .l)
    case .bit_1_pHL_4e: bit_pHL(1)
    case .bit_1_a_4f: bit_r(1, .a)
    case .bit_2_b_50: bit_r(2, .b)
    case .bit_2_c_51: bit_r(2, .c)
    case .bit_2_d_52: bit_r(2, .d)
    case .bit_2_e_53: bit_r(2, .e)
    case .bit_2_h_54: bit_r(2, .h)
    case .bit_2_l_55: bit_r(2, .l)
    case .bit_2_pHL_56: bit_pHL(2)
    case .bit_2_a_57: bit_r(2, .a)
    case .bit_3_b_58: bit_r(3, .b)
    case .bit_3_c_59: bit_r(3, .c)
    case .bit_3_d_5a: bit_r(3, .d)
    case .bit_3_e_5b: bit_r(3, .e)
    case .bit_3_h_5c: bit_r(3, .h)
    case .bit_3_l_5d: bit_r(3, .l)
    case .bit_3_pHL_5e: bit_pHL(3)
    case .bit_3_a_5f: bit_r(3, .a)
    case .bit_4_b_60: bit_r(4, .b)
    case .bit_4_c_61: bit_r(4, .c)
    case .bit_4_d_62: bit_r(4, .d)
    case .bit_4_e_63: bit_r(4, .e)
    case .bit_4_h_64: bit_r(4, .h)
    case .bit_4_l_65: bit_r(4, .l)
    case .bit_4_pHL_66: bit_pHL(4)
    case .bit_4_a_67: bit_r(4, .a)
    case .bit_5_b_68: bit_r(5, .b)
    case .bit_5_c_69: bit_r(5, .c)
    case .bit_5_d_6a: bit_r(5, .d)
    case .bit_5_e_6b: bit_r(5, .e)
    case .bit_5_h_6c: bit_r(5, .h)
    case .bit_5_l_6d: bit_r(5, .l)
    case .bit_5_pHL_6e: bit_pHL(5)
    case .bit_5_a_6f: bit_r(5, .a)
    case .bit_6_b_70: bit_r(6, .b)
    case .bit_6_c_71: bit_r(6, .c)
    case .bit_6_d_72: bit_r(6, .d)
    case .bit_6_e_73: bit_r(6, .e)
    case .bit_6_h_74: bit_r(6, .h)
    case .bit_6_l_75: bit_r(6, .l)
    case .bit_6_pHL_76: bit_pHL(6)
    case .bit_6_a_77: bit_r(6, .a)
    case .bit_7_b_78: bit_r(7, .b)
    case .bit_7_c_79: bit_r(7, .c)
    case .bit_7_d_7a: bit_r(7, .d)
    case .bit_7_e_7b: bit_r(7, .e)
    case .bit_7_h_7c: bit_r(7, .h)
    case .bit_7_l_7d: bit_r(7, .l)
    case .bit_7_pHL_7e: bit_pHL(7)
    case .bit_7_a_7f: bit_r(7, .a)
    case .res_0_b_80: res_r(0, .b)
    case .res_0_c_81: res_r(0, .c)
    case .res_0_d_82: res_r(0, .d)
    case .res_0_e_83: res_r(0, .e)
    case .res_0_h_84: res_r(0, .h)
    case .res_0_l_85: res_r(0, .l)
    case .res_0_pHL_86: res_pHL(0)
    case .res_0_a_87: res_r(0, .a)
    case .res_1_b_88: res_r(1, .b)
    case .res_1_c_89: res_r(1, .c)
    case .res_1_d_8a: res_r(1, .d)
    case .res_1_e_8b: res_r(1, .e)
    case .res_1_h_8c: res_r(1, .h)
    case .res_1_l_8d: res_r(1, .l)
    case .res_1_pHL_8e: res_pHL(1)
    case .res_1_a_8f: res_r(1, .a)
    case .res_2_b_90: res_r(2, .b)
    case .res_2_c_91: res_r(2, .c)
    case .res_2_d_92: res_r(2, .d)
    case .res_2_e_93: res_r(2, .e)
    case .res_2_h_94: res_r(2, .h)
    case .res_2_l_95: res_r(2, .l)
    case .res_2_pHL_96: res_pHL(2)
    case .res_2_a_97: res_r(2, .a)
    case .res_3_b_98: res_r(3, .b)
    case .res_3_c_99: res_r(3, .c)
    case .res_3_d_9a: res_r(3, .d)
    case .res_3_e_9b: res_r(3, .e)
    case .res_3_h_9c: res_r(3, .h)
    case .res_3_l_9d: res_r(3, .l)
    case .res_3_pHL_9e: res_pHL(3)
    case .res_3_a_9f: res_r(3, .a)
    case .res_4_b_a0: res_r(4, .b)
    case .res_4_c_a1: res_r(4, .c)
    case .res_4_d_a2: res_r(4, .d)
    case .res_4_e_a3: res_r(4, .e)
    case .res_4_h_a4: res_r(4, .h)
    case .res_4_l_a5: res_r(4, .l)
    case .res_4_pHL_a6: res_pHL(4)
    case .res_4_a_a7: res_r(4, .a)
    case .res_5_b_a8: res_r(5, .b)
    case .res_5_c_a9: res_r(5, .c)
    case .res_5_d_aa: res_r(5, .d)
    case .res_5_e_ab: res_r(5, .e)
    case .res_5_h_ac: res_r(5, .h)
    case .res_5_l_ad: res_r(5, .l)
    case .res_5_pHL_ae: res_pHL(5)
    case .res_5_a_af: res_r(5, .a)
    case .res_6_b_b0: res_r(6, .b)
    case .res_6_c_b1: res_r(6, .c)
    case .res_6_d_b2: res_r(6, .d)
    case .res_6_e_b3: res_r(6, .e)
    case .res_6_h_b4: res_r(6, .h)
    case .res_6_l_b5: res_r(6, .l)
    case .res_6_pHL_b6: res_pHL(6)
    case .res_6_a_b7: res_r(6, .a)
    case .res_7_b_b8: res_r(7, .b)
    case .res_7_c_b9: res_r(7, .c)
    case .res_7_d_ba: res_r(7, .d)
    case .res_7_e_bb: res_r(7, .e)
    case .res_7_h_bc: res_r(7, .h)
    case .res_7_l_bd: res_r(7, .l)
    case .res_7_pHL_be: res_pHL(7)
    case .res_7_a_bf: res_r(7, .a)
    case .set_0_b_c0: set_r(0, .b)
    case .set_0_c_c1: set_r(0, .c)
    case .set_0_d_c2: set_r(0, .d)
    case .set_0_e_c3: set_r(0, .e)
    case .set_0_h_c4: set_r(0, .h)
    case .set_0_l_c5: set_r(0, .l)
    case .set_0_pHL_c6: set_pHL(0)
    case .set_0_a_c7: set_r(0, .a)
    case .set_1_b_c8: set_r(1, .b)
    case .set_1_c_c9: set_r(1, .c)
    case .set_1_d_ca: set_r(1, .d)
    case .set_1_e_cb: set_r(1, .e)
    case .set_1_h_cc: set_r(1, .h)
    case .set_1_l_cd: set_r(1, .l)
    case .set_1_pHL_ce: set_pHL(1)
    case .set_1_a_cf: set_r(1, .a)
    case .set_2_b_d0: set_r(2, .b)
    case .set_2_c_d1: set_r(2, .c)
    case .set_2_d_d2: set_r(2, .d)
    case .set_2_e_d3: set_r(2, .e)
    case .set_2_h_d4: set_r(2, .h)
    case .set_2_l_d5: set_r(2, .l)
    case .set_2_pHL_d6: set_pHL(2)
    case .set_2_a_d7: set_r(2, .a)
    case .set_3_b_d8: set_r(3, .b)
    case .set_3_c_d9: set_r(3, .c)
    case .set_3_d_da: set_r(3, .d)
    case .set_3_e_db: set_r(3, .e)
    case .set_3_h_dc: set_r(3, .h)
    case .set_3_l_dd: set_r(3, .l)
    case .set_3_pHL_de: set_pHL(3)
    case .set_3_a_df: set_r(3, .a)
    case .set_4_b_e0: set_r(4, .b)
    case .set_4_c_e1: set_r(4, .c)
    case .set_4_d_e2: set_r(4, .d)
    case .set_4_e_e3: set_r(4, .e)
    case .set_4_h_e4: set_r(4, .h)
    case .set_4_l_e5: set_r(4, .l)
    case .set_4_pHL_e6: set_pHL(4)
    case .set_4_a_e7: set_r(4, .a)
    case .set_5_b_e8: set_r(5, .b)
    case .set_5_c_e9: set_r(5, .c)
    case .set_5_d_ea: set_r(5, .d)
    case .set_5_e_eb: set_r(5, .e)
    case .set_5_h_ec: set_r(5, .h)
    case .set_5_l_ed: set_r(5, .l)
    case .set_5_pHL_ee: set_pHL(5)
    case .set_5_a_ef: set_r(5, .a)
    case .set_6_b_f0: set_r(6, .b)
    case .set_6_c_f1: set_r(6, .c)
    case .set_6_d_f2: set_r(6, .d)
    case .set_6_e_f3: set_r(6, .e)
    case .set_6_h_f4: set_r(6, .h)
    case .set_6_l_f5: set_r(6, .l)
    case .set_6_pHL_f6: set_pHL(6)
    case .set_6_a_f7: set_r(6, .a)
    case .set_7_b_f8: set_r(7, .b)
    case .set_7_c_f9: set_r(7, .c)
    case .set_7_d_fa: set_r(7, .d)
    case .set_7_e_fb: set_r(7, .e)
    case .set_7_h_fc: set_r(7, .h)
    case .set_7_l_fd: set_r(7, .l)
    case .set_7_pHL_fe: set_pHL(7)
    case .set_7_a_ff: set_r(7, .a)
    }
  }
}
