// This file was auto-generated.
// DO NOT EDIT!

// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length
// swiftlint:disable function_body_length
// swiftlint:disable cyclomatic_complexity
// swiftlint:disable switch_case_alignment

extension Cpu {
  mutating func execute(_ opcode: PrefixOpcode) {
    switch opcode.type {
/* 0x0 */ case .rlc_b: self.rlc_r(.b)
/* 0x1 */ case .rlc_c: self.rlc_r(.c)
/* 0x2 */ case .rlc_d: self.rlc_r(.d)
/* 0x3 */ case .rlc_e: self.rlc_r(.e)
/* 0x4 */ case .rlc_h: self.rlc_r(.h)
/* 0x5 */ case .rlc_l: self.rlc_r(.l)
/* 0x6 */ case .rlc_pHL: self.rlc_pHL()
/* 0x7 */ case .rlc_a: self.rlc_r(.a)
/* 0x8 */ case .rrc_b: self.rrc_r(.b)
/* 0x9 */ case .rrc_c: self.rrc_r(.c)
/* 0xa */ case .rrc_d: self.rrc_r(.d)
/* 0xb */ case .rrc_e: self.rrc_r(.e)
/* 0xc */ case .rrc_h: self.rrc_r(.h)
/* 0xd */ case .rrc_l: self.rrc_r(.l)
/* 0xe */ case .rrc_pHL: self.rrc_pHL()
/* 0xf */ case .rrc_a: self.rrc_r(.a)
/* 0x10 */ case .rl_b: self.rl_r(.b)
/* 0x11 */ case .rl_c: self.rl_r(.c)
/* 0x12 */ case .rl_d: self.rl_r(.d)
/* 0x13 */ case .rl_e: self.rl_r(.e)
/* 0x14 */ case .rl_h: self.rl_r(.h)
/* 0x15 */ case .rl_l: self.rl_r(.l)
/* 0x16 */ case .rl_pHL: self.rl_pHL()
/* 0x17 */ case .rl_a: self.rl_r(.a)
/* 0x18 */ case .rr_b: self.rr_r(.b)
/* 0x19 */ case .rr_c: self.rr_r(.c)
/* 0x1a */ case .rr_d: self.rr_r(.d)
/* 0x1b */ case .rr_e: self.rr_r(.e)
/* 0x1c */ case .rr_h: self.rr_r(.h)
/* 0x1d */ case .rr_l: self.rr_r(.l)
/* 0x1e */ case .rr_pHL: self.rr_pHL()
/* 0x1f */ case .rr_a: self.rr_r(.a)
/* 0x20 */ case .sla_b: self.sla_r(.b)
/* 0x21 */ case .sla_c: self.sla_r(.c)
/* 0x22 */ case .sla_d: self.sla_r(.d)
/* 0x23 */ case .sla_e: self.sla_r(.e)
/* 0x24 */ case .sla_h: self.sla_r(.h)
/* 0x25 */ case .sla_l: self.sla_r(.l)
/* 0x26 */ case .sla_pHL: self.sla_pHL()
/* 0x27 */ case .sla_a: self.sla_r(.a)
/* 0x28 */ case .sra_b: self.sra_r(.b)
/* 0x29 */ case .sra_c: self.sra_r(.c)
/* 0x2a */ case .sra_d: self.sra_r(.d)
/* 0x2b */ case .sra_e: self.sra_r(.e)
/* 0x2c */ case .sra_h: self.sra_r(.h)
/* 0x2d */ case .sra_l: self.sra_r(.l)
/* 0x2e */ case .sra_pHL: self.sra_pHL()
/* 0x2f */ case .sra_a: self.sra_r(.a)
/* 0x30 */ case .swap_b: self.swap_r(.b)
/* 0x31 */ case .swap_c: self.swap_r(.c)
/* 0x32 */ case .swap_d: self.swap_r(.d)
/* 0x33 */ case .swap_e: self.swap_r(.e)
/* 0x34 */ case .swap_h: self.swap_r(.h)
/* 0x35 */ case .swap_l: self.swap_r(.l)
/* 0x36 */ case .swap_pHL: self.swap_pHL()
/* 0x37 */ case .swap_a: self.swap_r(.a)
/* 0x38 */ case .srl_b: self.srl_r(.b)
/* 0x39 */ case .srl_c: self.srl_r(.c)
/* 0x3a */ case .srl_d: self.srl_r(.d)
/* 0x3b */ case .srl_e: self.srl_r(.e)
/* 0x3c */ case .srl_h: self.srl_r(.h)
/* 0x3d */ case .srl_l: self.srl_r(.l)
/* 0x3e */ case .srl_pHL: self.srl_pHL()
/* 0x3f */ case .srl_a: self.srl_r(.a)
/* 0x40 */ case .bit_0_b: self.bit_r(0, .b)
/* 0x41 */ case .bit_0_c: self.bit_r(0, .c)
/* 0x42 */ case .bit_0_d: self.bit_r(0, .d)
/* 0x43 */ case .bit_0_e: self.bit_r(0, .e)
/* 0x44 */ case .bit_0_h: self.bit_r(0, .h)
/* 0x45 */ case .bit_0_l: self.bit_r(0, .l)
/* 0x46 */ case .bit_0_pHL: self.bit_pHL(0)
/* 0x47 */ case .bit_0_a: self.bit_r(0, .a)
/* 0x48 */ case .bit_1_b: self.bit_r(1, .b)
/* 0x49 */ case .bit_1_c: self.bit_r(1, .c)
/* 0x4a */ case .bit_1_d: self.bit_r(1, .d)
/* 0x4b */ case .bit_1_e: self.bit_r(1, .e)
/* 0x4c */ case .bit_1_h: self.bit_r(1, .h)
/* 0x4d */ case .bit_1_l: self.bit_r(1, .l)
/* 0x4e */ case .bit_1_pHL: self.bit_pHL(1)
/* 0x4f */ case .bit_1_a: self.bit_r(1, .a)
/* 0x50 */ case .bit_2_b: self.bit_r(2, .b)
/* 0x51 */ case .bit_2_c: self.bit_r(2, .c)
/* 0x52 */ case .bit_2_d: self.bit_r(2, .d)
/* 0x53 */ case .bit_2_e: self.bit_r(2, .e)
/* 0x54 */ case .bit_2_h: self.bit_r(2, .h)
/* 0x55 */ case .bit_2_l: self.bit_r(2, .l)
/* 0x56 */ case .bit_2_pHL: self.bit_pHL(2)
/* 0x57 */ case .bit_2_a: self.bit_r(2, .a)
/* 0x58 */ case .bit_3_b: self.bit_r(3, .b)
/* 0x59 */ case .bit_3_c: self.bit_r(3, .c)
/* 0x5a */ case .bit_3_d: self.bit_r(3, .d)
/* 0x5b */ case .bit_3_e: self.bit_r(3, .e)
/* 0x5c */ case .bit_3_h: self.bit_r(3, .h)
/* 0x5d */ case .bit_3_l: self.bit_r(3, .l)
/* 0x5e */ case .bit_3_pHL: self.bit_pHL(3)
/* 0x5f */ case .bit_3_a: self.bit_r(3, .a)
/* 0x60 */ case .bit_4_b: self.bit_r(4, .b)
/* 0x61 */ case .bit_4_c: self.bit_r(4, .c)
/* 0x62 */ case .bit_4_d: self.bit_r(4, .d)
/* 0x63 */ case .bit_4_e: self.bit_r(4, .e)
/* 0x64 */ case .bit_4_h: self.bit_r(4, .h)
/* 0x65 */ case .bit_4_l: self.bit_r(4, .l)
/* 0x66 */ case .bit_4_pHL: self.bit_pHL(4)
/* 0x67 */ case .bit_4_a: self.bit_r(4, .a)
/* 0x68 */ case .bit_5_b: self.bit_r(5, .b)
/* 0x69 */ case .bit_5_c: self.bit_r(5, .c)
/* 0x6a */ case .bit_5_d: self.bit_r(5, .d)
/* 0x6b */ case .bit_5_e: self.bit_r(5, .e)
/* 0x6c */ case .bit_5_h: self.bit_r(5, .h)
/* 0x6d */ case .bit_5_l: self.bit_r(5, .l)
/* 0x6e */ case .bit_5_pHL: self.bit_pHL(5)
/* 0x6f */ case .bit_5_a: self.bit_r(5, .a)
/* 0x70 */ case .bit_6_b: self.bit_r(6, .b)
/* 0x71 */ case .bit_6_c: self.bit_r(6, .c)
/* 0x72 */ case .bit_6_d: self.bit_r(6, .d)
/* 0x73 */ case .bit_6_e: self.bit_r(6, .e)
/* 0x74 */ case .bit_6_h: self.bit_r(6, .h)
/* 0x75 */ case .bit_6_l: self.bit_r(6, .l)
/* 0x76 */ case .bit_6_pHL: self.bit_pHL(6)
/* 0x77 */ case .bit_6_a: self.bit_r(6, .a)
/* 0x78 */ case .bit_7_b: self.bit_r(7, .b)
/* 0x79 */ case .bit_7_c: self.bit_r(7, .c)
/* 0x7a */ case .bit_7_d: self.bit_r(7, .d)
/* 0x7b */ case .bit_7_e: self.bit_r(7, .e)
/* 0x7c */ case .bit_7_h: self.bit_r(7, .h)
/* 0x7d */ case .bit_7_l: self.bit_r(7, .l)
/* 0x7e */ case .bit_7_pHL: self.bit_pHL(7)
/* 0x7f */ case .bit_7_a: self.bit_r(7, .a)
/* 0x80 */ case .res_0_b: self.res_r(0, .b)
/* 0x81 */ case .res_0_c: self.res_r(0, .c)
/* 0x82 */ case .res_0_d: self.res_r(0, .d)
/* 0x83 */ case .res_0_e: self.res_r(0, .e)
/* 0x84 */ case .res_0_h: self.res_r(0, .h)
/* 0x85 */ case .res_0_l: self.res_r(0, .l)
/* 0x86 */ case .res_0_pHL: self.res_pHL(0)
/* 0x87 */ case .res_0_a: self.res_r(0, .a)
/* 0x88 */ case .res_1_b: self.res_r(1, .b)
/* 0x89 */ case .res_1_c: self.res_r(1, .c)
/* 0x8a */ case .res_1_d: self.res_r(1, .d)
/* 0x8b */ case .res_1_e: self.res_r(1, .e)
/* 0x8c */ case .res_1_h: self.res_r(1, .h)
/* 0x8d */ case .res_1_l: self.res_r(1, .l)
/* 0x8e */ case .res_1_pHL: self.res_pHL(1)
/* 0x8f */ case .res_1_a: self.res_r(1, .a)
/* 0x90 */ case .res_2_b: self.res_r(2, .b)
/* 0x91 */ case .res_2_c: self.res_r(2, .c)
/* 0x92 */ case .res_2_d: self.res_r(2, .d)
/* 0x93 */ case .res_2_e: self.res_r(2, .e)
/* 0x94 */ case .res_2_h: self.res_r(2, .h)
/* 0x95 */ case .res_2_l: self.res_r(2, .l)
/* 0x96 */ case .res_2_pHL: self.res_pHL(2)
/* 0x97 */ case .res_2_a: self.res_r(2, .a)
/* 0x98 */ case .res_3_b: self.res_r(3, .b)
/* 0x99 */ case .res_3_c: self.res_r(3, .c)
/* 0x9a */ case .res_3_d: self.res_r(3, .d)
/* 0x9b */ case .res_3_e: self.res_r(3, .e)
/* 0x9c */ case .res_3_h: self.res_r(3, .h)
/* 0x9d */ case .res_3_l: self.res_r(3, .l)
/* 0x9e */ case .res_3_pHL: self.res_pHL(3)
/* 0x9f */ case .res_3_a: self.res_r(3, .a)
/* 0xa0 */ case .res_4_b: self.res_r(4, .b)
/* 0xa1 */ case .res_4_c: self.res_r(4, .c)
/* 0xa2 */ case .res_4_d: self.res_r(4, .d)
/* 0xa3 */ case .res_4_e: self.res_r(4, .e)
/* 0xa4 */ case .res_4_h: self.res_r(4, .h)
/* 0xa5 */ case .res_4_l: self.res_r(4, .l)
/* 0xa6 */ case .res_4_pHL: self.res_pHL(4)
/* 0xa7 */ case .res_4_a: self.res_r(4, .a)
/* 0xa8 */ case .res_5_b: self.res_r(5, .b)
/* 0xa9 */ case .res_5_c: self.res_r(5, .c)
/* 0xaa */ case .res_5_d: self.res_r(5, .d)
/* 0xab */ case .res_5_e: self.res_r(5, .e)
/* 0xac */ case .res_5_h: self.res_r(5, .h)
/* 0xad */ case .res_5_l: self.res_r(5, .l)
/* 0xae */ case .res_5_pHL: self.res_pHL(5)
/* 0xaf */ case .res_5_a: self.res_r(5, .a)
/* 0xb0 */ case .res_6_b: self.res_r(6, .b)
/* 0xb1 */ case .res_6_c: self.res_r(6, .c)
/* 0xb2 */ case .res_6_d: self.res_r(6, .d)
/* 0xb3 */ case .res_6_e: self.res_r(6, .e)
/* 0xb4 */ case .res_6_h: self.res_r(6, .h)
/* 0xb5 */ case .res_6_l: self.res_r(6, .l)
/* 0xb6 */ case .res_6_pHL: self.res_pHL(6)
/* 0xb7 */ case .res_6_a: self.res_r(6, .a)
/* 0xb8 */ case .res_7_b: self.res_r(7, .b)
/* 0xb9 */ case .res_7_c: self.res_r(7, .c)
/* 0xba */ case .res_7_d: self.res_r(7, .d)
/* 0xbb */ case .res_7_e: self.res_r(7, .e)
/* 0xbc */ case .res_7_h: self.res_r(7, .h)
/* 0xbd */ case .res_7_l: self.res_r(7, .l)
/* 0xbe */ case .res_7_pHL: self.res_pHL(7)
/* 0xbf */ case .res_7_a: self.res_r(7, .a)
/* 0xc0 */ case .set_0_b: self.set_r(0, .b)
/* 0xc1 */ case .set_0_c: self.set_r(0, .c)
/* 0xc2 */ case .set_0_d: self.set_r(0, .d)
/* 0xc3 */ case .set_0_e: self.set_r(0, .e)
/* 0xc4 */ case .set_0_h: self.set_r(0, .h)
/* 0xc5 */ case .set_0_l: self.set_r(0, .l)
/* 0xc6 */ case .set_0_pHL: self.set_pHL(0)
/* 0xc7 */ case .set_0_a: self.set_r(0, .a)
/* 0xc8 */ case .set_1_b: self.set_r(1, .b)
/* 0xc9 */ case .set_1_c: self.set_r(1, .c)
/* 0xca */ case .set_1_d: self.set_r(1, .d)
/* 0xcb */ case .set_1_e: self.set_r(1, .e)
/* 0xcc */ case .set_1_h: self.set_r(1, .h)
/* 0xcd */ case .set_1_l: self.set_r(1, .l)
/* 0xce */ case .set_1_pHL: self.set_pHL(1)
/* 0xcf */ case .set_1_a: self.set_r(1, .a)
/* 0xd0 */ case .set_2_b: self.set_r(2, .b)
/* 0xd1 */ case .set_2_c: self.set_r(2, .c)
/* 0xd2 */ case .set_2_d: self.set_r(2, .d)
/* 0xd3 */ case .set_2_e: self.set_r(2, .e)
/* 0xd4 */ case .set_2_h: self.set_r(2, .h)
/* 0xd5 */ case .set_2_l: self.set_r(2, .l)
/* 0xd6 */ case .set_2_pHL: self.set_pHL(2)
/* 0xd7 */ case .set_2_a: self.set_r(2, .a)
/* 0xd8 */ case .set_3_b: self.set_r(3, .b)
/* 0xd9 */ case .set_3_c: self.set_r(3, .c)
/* 0xda */ case .set_3_d: self.set_r(3, .d)
/* 0xdb */ case .set_3_e: self.set_r(3, .e)
/* 0xdc */ case .set_3_h: self.set_r(3, .h)
/* 0xdd */ case .set_3_l: self.set_r(3, .l)
/* 0xde */ case .set_3_pHL: self.set_pHL(3)
/* 0xdf */ case .set_3_a: self.set_r(3, .a)
/* 0xe0 */ case .set_4_b: self.set_r(4, .b)
/* 0xe1 */ case .set_4_c: self.set_r(4, .c)
/* 0xe2 */ case .set_4_d: self.set_r(4, .d)
/* 0xe3 */ case .set_4_e: self.set_r(4, .e)
/* 0xe4 */ case .set_4_h: self.set_r(4, .h)
/* 0xe5 */ case .set_4_l: self.set_r(4, .l)
/* 0xe6 */ case .set_4_pHL: self.set_pHL(4)
/* 0xe7 */ case .set_4_a: self.set_r(4, .a)
/* 0xe8 */ case .set_5_b: self.set_r(5, .b)
/* 0xe9 */ case .set_5_c: self.set_r(5, .c)
/* 0xea */ case .set_5_d: self.set_r(5, .d)
/* 0xeb */ case .set_5_e: self.set_r(5, .e)
/* 0xec */ case .set_5_h: self.set_r(5, .h)
/* 0xed */ case .set_5_l: self.set_r(5, .l)
/* 0xee */ case .set_5_pHL: self.set_pHL(5)
/* 0xef */ case .set_5_a: self.set_r(5, .a)
/* 0xf0 */ case .set_6_b: self.set_r(6, .b)
/* 0xf1 */ case .set_6_c: self.set_r(6, .c)
/* 0xf2 */ case .set_6_d: self.set_r(6, .d)
/* 0xf3 */ case .set_6_e: self.set_r(6, .e)
/* 0xf4 */ case .set_6_h: self.set_r(6, .h)
/* 0xf5 */ case .set_6_l: self.set_r(6, .l)
/* 0xf6 */ case .set_6_pHL: self.set_pHL(6)
/* 0xf7 */ case .set_6_a: self.set_r(6, .a)
/* 0xf8 */ case .set_7_b: self.set_r(7, .b)
/* 0xf9 */ case .set_7_c: self.set_r(7, .c)
/* 0xfa */ case .set_7_d: self.set_r(7, .d)
/* 0xfb */ case .set_7_e: self.set_r(7, .e)
/* 0xfc */ case .set_7_h: self.set_r(7, .h)
/* 0xfd */ case .set_7_l: self.set_r(7, .l)
/* 0xfe */ case .set_7_pHL: self.set_pHL(7)
/* 0xff */ case .set_7_a: self.set_r(7, .a)
    }
  }
}
